name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check formatting
        run: make format
      - name: Build
        run: make build
      - name: Test
        run: make test